### GENERAL SETTINGS ###

# Site settings
#You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
title: Kaito Tech
description: "Kaito Tech optimize your cloud solution. Stop scheduling your cloud Kaito Tech will help you with automation."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://kaito.tech"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url:
  - title: facebook
    url:
  - title: linkedin
    url:
  - title: instagram
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Via Aurelio Saliceti, 10,
    - 00153, Rome,
    - Italy. 🇮🇹
email: master@kaito.tech
tel: +39 000-000


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Tommaso Doninelli
    position: CTO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: Red Ninja #use for email address
        url: mailto:tommaso@kaito.tech
      - title: twitter
        url: http://twitter.com/handle
  - name: Paul Jameson
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Ahmed Abdel Rahman
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team03.jpg
    social:
      - title: Blue Ninja #use for email address
        url: mailto:ahmed@kaito.tech
      - title: twitter
        url: http://twitter.com/AhmedBarkhia
  - name: Martin Blunt
    position: Marketing
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Automagically dispose cloud resources if no one is using them. Automagically start cloud resources if customer requests are incoming!"

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Kaito Tech is exactly what an IT Dept must have when using cloud computing. It is simple, direct and provides the expected actions. Besides that, the Kaito Tech ninjas are helpful and open for new ideas."
    author: Ajay Seth
    position: Head of Core Technology and Development - kinetikos.io
